### ISSUE TITLE
Compiling problems...

### ISSUE THREAD

**Issue by kanegil** [Caig/kde-thumbnailer-epub#3]
After executing "cmake -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` .." I keep getting the following errors:

_CMake Warning at /usr/share/ECM/modules/ECMQueryQmake.cmake:22 (message):
  Failed call: qmake-qt5 -query "QT_INSTALL_PLUGINS"
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:432 (query_qmake)
  CMakeLists.txt:10 (include)_

_CMake Error at /usr/share/ECM/modules/ECMQueryQmake.cmake:23 (message):
  QMake call failed: No such file or directory
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:432 (query_qmake)
  CMakeLists.txt:10 (include)_

I'm currently running Kubuntu 16.04 64-bit with Plasma 5.5.5 and Qt 5.5.1. Anyone have any suggestions as to what's going wrong here? I'm not the most proficient with compiling so any help is appreciated.

Thx

**Comment by Caig** [comment]
Hi, are you sure you installed the needed packages to compile KDE/Qt apps on your distribution? Sorry, but I can't be more precise because I never used Kubuntu.

**Comment by kanegil** [comment]
Thanks for your reply. I've installed cmake, extra-cmake-modules, cmake-extras, qt5-make and a package called build-essentials. I don't know what else to install or what I could be missing. I had the older epub thumbnailer compiled and running just fine on my KDE 4 system, but I just can't seem to get this newer one to work on my fresh install.

**Comment by Caig** [comment]
It seems qmake[1] doesn't find a Qt directory, maybe you can try to install qtcreator, the package should require all the needed ones to compile Qt apps.

[1]`qmake-qt5 -query "QT_INSTALL_PLUGINS"` in a console should return something like `/usr/lib/qt/plugins`

**Comment by kanegil** [comment]
`qmake-qt5 -query "QT_INSTALL_PLUGINS"`  returns the following:
No command 'qmake-qt5' found, did you mean:
 Command 'qmake-qt4' from package 'qt4-qmake' (main)
qmake-qt5: command not found

I have found qt plugins in `/usr/lib/x86_64-linux-gnu/qt5/plugins/`. qmake is clearly installed on my system, so I really can't figure out what's going on here. Google hasn't been much help and I really don't know what to do. Maybe I just don't get to have epub thumbnails.  :-(

**Comment by Caig** [comment]
Is it possible that the executable it's just named `qmake`?
http://packages.ubuntu.com/xenial/amd64/qt5-qmake/filelist

In that case I don't understand why Kubuntu try to execute `qmake-qt5`

**Comment by Caig** [comment]
Distro related issue imo
